<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SatkerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('satuan_kerjas')->insert([
            ['satker' => 'Sekretariat Direktorat Jendral'],
            ['satker' => 'Direktorat Interdiksi Narkotika'],
            ['satker' => 'Kanwil DJBC Aceh'],
            ['satker' => 'KPPBC TMP C Sabang'],
            ['satker' => 'KPPBC TMP C Banda Aceh'],
            ['satker' => 'KPPBC TMP C Meulaboh'],
            ['satker' => 'KPPBC TMP C Lhokseumawe'],
            ['satker' => 'KPPBC TMP C Langsa'],
            ['satker' => 'Kanwil DJBC Sumatera Utara'],
            ['satker' => 'KPPBC TMP Belawan'],
            ['satker' => 'KPPBC TMP B Medan'],
            ['satker' => 'KPPBC TMP C Pematangsiantar'],
            ['satker' => 'KPPBC TMP C Sibolga'],
            ['satker' => 'KPPBC TMP C Teluk Nibung'],
            ['satker' => 'KPPBC TMP C Kuala Tanjung'],
            ['satker' => 'KPPBC TMP B Kualanamu'],
            ['satker' => 'Kanwil DJBC Riau'],
            ['satker' => 'KPPBC TMP B Pekanbaru'],
            ['satker' => 'KPPBC TMP B Dumai'],
            ['satker' => 'KPPBC TMP C Tembilahan'],
            ['satker' => 'KPPBC TMP C Bengkalis'],
            ['satker' => 'Kanwil DJBC Khusus Kepulauan Riau'],
            ['satker' => 'KPPBC TMP B Tanjung Balai Karimun'],
            ['satker' => 'KPPBC TMP B Tanjung Pinang'],
            ['satker' => 'PSO BC Tipe A Tanjung Balai Karimun'],
            ['satker' => 'Kanwil DJBC Sumatera Bagian Timur'],
            ['satker' => 'KPPBC TMP B Palembang'],
            ['satker' => 'KPPBC TMP B Jambi'],
            ['satker' => 'KPPBC TMP C Pangkalpinang'],
            ['satker' => 'KPPBC TMP C Tanjungpandan'],
            ['satker' => 'Kanwil DJBC Sumatera Bagian Barat'],
            ['satker' => 'KPPBC TMP B Teluk Bayur'],
            ['satker' => 'KPPBC TMP C Bengkulu'],
            ['satker' => 'KPPBC TMP B Bandar Lampung'],
            ['satker' => 'Kanwil BJBC Banten'],
            ['satker' => 'KPPBC TMP Merak'],
            ['satker' => 'KPPBC TMP A Tangerang'],
            ['satker' => 'Kanwil DJBC Jakarta'],
            ['satker' => 'KPPBC TMP A Jakarta'],
            ['satker' => 'KPPBC TMP A Marunda'],
            ['satker' => 'KPPBC TMP C Kantor Pos Pasar Baru'],
            ['satker' => 'KPPBC TMP B Tanjung Priok'],
            ['satker' => 'Kanwil DJBC Jawa Barat'],
            ['satker' => 'KPPBC TMP A Bekasi'],
            ['satker' => 'KPPBC TMP A Bogor'],
            ['satker' => 'KPPBC TMP A Purwakarta'],
            ['satker' => 'KPPBC TMP A Bandung'],
            ['satker' => 'KPPBC TMP B Cirebon'],
            ['satker' => 'KPPBC TMP C Tasikmalaya'],
            ['satker' => 'KPPBC TMP Cikarang'],
            ['satker' => 'Kanwil DJBC Jawa Tengah dan DIY'],
            ['satker' => 'KPPBC TMP Tanjung Emas'],
            ['satker' => 'KPPBC TMP Kudus'],
            ['satker' => 'KPPBC TMP B Surakarta'],
            ['satker' => 'KPPBC TMP C Cilacap'],
            ['satker' => 'KPPBC TMP C Purwokerto'],
            ['satker' => 'KPPBC TMP C Tegal'],
            ['satker' => 'KPPBC TMP A Semarang'],
            ['satker' => 'KPPBC TMP B Yogyakarta'],
            ['satker' => 'KPPBC TMP C Magelang'],
            ['satker' => 'Kanwil DJBC Jawa Timur I'],
            ['satker' => 'KPPBC TMP Tanjung Perak'],
            ['satker' => 'KPPBC TMP A Pasuruan'],
            ['satker' => 'KPPBC TMP Juanda'],
            ['satker' => 'KPPBC TMP B Gresik'],
            ['satker' => 'KPPBC TMP C Madura'],
            ['satker' => 'KPPBC TMP C Bojonegoro'],
            ['satker' => 'KPPBC TMP B Sidoarjo'],
            ['satker' => 'Kanwil DJBC Jawa Timur II'],
            ['satker' => 'KPPBC TMP Malang'],
            ['satker' => 'KPPBC TMP Kediri '],
            ['satker' => 'KPPBC TMP C Blitar'],
            ['satker' => 'KPPBC TMP C Madiun'],
            ['satker' => 'KPPBC TMP C Jember'],
            ['satker' => 'KPPBC TMP C Banyuwangi'],
            ['satker' => 'KPPBC TMP C Probolinggo'],
            ['satker' => 'Kanwil DJBC Bali, NTB dan NTT'],
            ['satker' => 'KPPBC TMP Ngurah Rai'],
            ['satker' => 'KPPBC TMP A Denpasar'],
            ['satker' => 'KPPBC TMP C Mataram'],
            ['satker' => 'KPPBC TMP C Sumbawa'],
            ['satker' => 'KPPBC TMP C Kupang'],
            ['satker' => 'KPPBC TMP B Atambua'],
            ['satker' => 'KPPBC TMP C Labuan Bajo'],
            ['satker' => 'Kanwil DJBC Kalimantan Bagian Barat'],
            ['satker' => 'KPPBC TMP B Pontianak'],
            ['satker' => 'KPPBC TMP C Entikong'],
            ['satker' => 'KPPBC TMP C Nanga Badau'],
            ['satker' => 'KPPBC TMP C Sintete'],
            ['satker' => 'KPPBC TMP C Ketapang'],
            ['satker' => 'KPPBC TMP C Jagoi Babang'],
            ['satker' => 'Kanwil DJBC Kalimantan Bagian Selatan'],
            ['satker' => 'KPPBC TMP B Banjarmasing'],
            ['satker' => 'KPPBC TMP C Sampit'],
            ['satker' => 'KPPBC TMP C Pangkalan Bun'],
            ['satker' => 'KPPBC TMP C Palangkaraya'],
            ['satker' => 'KPPBC TMP C Kotabaru'],
            ['satker' => 'Kanwil DJBC Bagian Timur'],
            ['satker' => 'KPPBC TMP B Balikpapan'],
            ['satker' => 'KPPBC TMP B Samarinda'],
            ['satker' => 'KPPBC TMP C Bontang'],
            ['satker' => 'KPPBC TMP C Sangatta'],
            ['satker' => 'KPPBC TMP B Tarakan'],
            ['satker' => 'KPPBC TMP C Nunukan'],
            ['satker' => 'Kanwil DJBC Sulawesi Bagian Selatan'],
            ['satker' => 'KPPBC TMP B Makassar'],
            ['satker' => 'KPPBC TMP C Parepare'],
            ['satker' => 'KPPBC TMP C Malili'],
            ['satker' => 'KPPBC TMP C Kendari'],
            ['satker' => 'Kanwil DJBC Sulawesi Bagian Utara'],
            ['satker' => 'KPPBC TMP C Pantoloan'],
            ['satker' => 'KPPBC TMP C Morowali'],
            ['satker' => 'KPPBC TMP C Luwuk'],
            ['satker' => 'KPPBC TMP C Bitung'],
            ['satker' => 'KPPBC TMP C Manado'],
            ['satker' => 'KPPBC TMP C Gorontalo'],
            ['satker' => 'KPPBC TMP B Pantoloan'],
            ['satker' => 'Kanwil DJBC Maluku'],
            ['satker' => 'KPPBC TMP C Ambon'],
            ['satker' => 'KPPBC TMP C Tual'],
            ['satker' => 'KPPBC TMP C Ternate'],
            ['satker' => 'Kanwil DJBC Khusus Papua'],
            ['satker' => 'KPPBC TMP C Sorong'],
            ['satker' => 'KPPBC TMP C Manokwari'],
            ['satker' => 'KPPBC TMP C Fakfak'],
            ['satker' => 'KPPBC TMP C Jayapura'],
            ['satker' => 'KPPBC TMP C Timika'],
            ['satker' => 'KPPBC TMP C Biak'],
            ['satker' => 'KPPBC TMP C Merauke'],
            ['satker' => 'KPPBC TMP B Sorong'],
            ['satker' => 'KPU BC Tipe A Tanjung Priok'],
            ['satker' => 'KPU BC Tipe B Batam'],
            ['satker' => 'PSO BC Tipe B Batam'],
            ['satker' => 'KPU BC Tipe C Soekarno-Hatta'],
        ]);
    }
}
